source 'https://rubygems.org'

gem 'rails', '6.0.2.rc2'

gem 'sqlite3'
gem 'overcommit'
gem 'brakeman'

group :development do
  gem 'dawnscanner', require: false
end

group :test do
  gem 'rails-controller-testing'
end
